import { StyleSheet } from "react-native";

import {
  ActionColors,
  AppHeaderHeight,
  CompactScreenTopMargin,
  MaxContentWidth,
  PageTopPadding,
  Spacing,
} from "@/constants/theme";

export const matchDayStyles = StyleSheet.create({
  scrollView: {
    flex: 1,
  },
  contentContainer: {
    flexDirection: "row",
    justifyContent: "center",
  },
  container: {
    flexGrow: 1,
    gap: Spacing.four,
    maxWidth: MaxContentWidth,
    marginTop: CompactScreenTopMargin,
    paddingHorizontal: Spacing.four,
    paddingTop: AppHeaderHeight + PageTopPadding,
  },
  header: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: Spacing.three,
    justifyContent: "space-between",
    paddingTop: PageTopPadding,
  },
  titleGroup: {
    flex: 1,
    gap: Spacing.two,
  },
  title: {
    lineHeight: 38,
  },
  description: {
    maxWidth: 560,
  },
  addMatchButton: {
    alignItems: "center",
    backgroundColor: "#1C7C54",
    borderRadius: Spacing.three,
    flexDirection: "row",
    gap: Spacing.one,
    minHeight: 44,
    paddingHorizontal: Spacing.three,
  },
  addMatchButtonText: {
    color: "#ffffff",
  },
  pressed: {
    opacity: 0.7,
  },
  panel: {
    borderRadius: Spacing.three,
    gap: Spacing.two,
    padding: Spacing.three,
  },
  emptyMatchPanel: {
    borderRadius: Spacing.three,
    gap: Spacing.two,
    padding: Spacing.three,
  },
  matchCardList: {
    gap: Spacing.three,
  },
  matchSection: {
    gap: Spacing.two,
  },
  matchSectionHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: Spacing.two,
    justifyContent: "space-between",
    minHeight: 24,
  },
  matchSectionList: {
    gap: Spacing.three,
  },
  matchCard: {
    borderRadius: Spacing.three,
    gap: Spacing.two,
    padding: Spacing.three,
    position: "relative",
  },
  matchCardHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: Spacing.two,
    justifyContent: "space-between",
    minHeight: 56,
  },
  matchCardTitleGroup: {
    flex: 1,
    gap: Spacing.half,
  },
  matchTitleRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: Spacing.one,
  },
  matchActionDueDot: {
    backgroundColor: ActionColors.warning,
    borderColor: "#ffffff",
    borderRadius: 999,
    borderWidth: 2,
    height: 20,
    position: "absolute",
    right: -5,
    top: -5,
    width: 20,
    zIndex: 3,
  },
  matchTitleText: {
    flexShrink: 1,
  },
  matchCardMetaGroup: {
    alignItems: "flex-end",
    gap: Spacing.half,
  },
  matchCardDetails: {
    gap: Spacing.three,
    paddingTop: Spacing.two,
  },
  matchCardActions: {
    alignItems: "center",
    alignSelf: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.two,
    justifyContent: "center",
    maxWidth: 520,
    width: "100%",
  },
  matchResultPanel: {
    borderRadius: Spacing.two,
    gap: Spacing.one,
    padding: Spacing.two,
  },
  matchResultScore: {
    lineHeight: 34,
  },
  shareMatchButton: {
    alignItems: "center",
    backgroundColor: ActionColors.warning,
    borderRadius: Spacing.two,
    flex: 1,
    flexDirection: "row",
    gap: Spacing.one,
    justifyContent: "center",
    minHeight: 40,
    minWidth: 116,
    paddingHorizontal: Spacing.two,
  },
  shareMatchButtonText: {
    color: "#ffffff",
  },
  resultMatchButton: {
    alignItems: "center",
    backgroundColor: "#1C7C54",
    borderRadius: Spacing.two,
    flex: 1,
    flexDirection: "row",
    gap: Spacing.one,
    justifyContent: "center",
    minHeight: 40,
    minWidth: 116,
    paddingHorizontal: Spacing.two,
  },
  resultMatchButtonText: {
    color: "#ffffff",
  },
  editResultMatchButton: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderColor: ActionColors.primary,
    borderRadius: Spacing.two,
    borderWidth: 1.5,
    flex: 1,
    flexDirection: "row",
    gap: Spacing.one,
    justifyContent: "center",
    minHeight: 40,
    minWidth: 116,
    paddingHorizontal: Spacing.two,
  },
  editResultMatchButtonText: {
    color: ActionColors.primary,
  },
  editMatchButton: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderColor: ActionColors.warning,
    borderRadius: Spacing.two,
    borderWidth: 1.5,
    flexDirection: "row",
    gap: Spacing.one,
    justifyContent: "center",
    minHeight: 48,
    minWidth: 116,
    paddingHorizontal: Spacing.three,
    paddingVertical: Spacing.one,
    flex: 1,
  },
  editMatchButtonText: {
    color: ActionColors.warning,
    flexShrink: 1,
    lineHeight: 18,
    textAlign: "center",
  },
  deleteMatchButton: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderColor: "#DC2626",
    borderRadius: Spacing.two,
    borderWidth: 1.5,
    flexDirection: "row",
    gap: Spacing.one,
    justifyContent: "center",
    minHeight: 48,
    minWidth: 116,
    paddingHorizontal: Spacing.three,
    paddingVertical: Spacing.one,
    flex: 1,
  },
  deleteMatchButtonText: {
    color: "#DC2626",
    flexShrink: 1,
    lineHeight: 18,
    textAlign: "center",
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
  },
  modalBackdrop: {
    backgroundColor: "rgba(0, 0, 0, 0.45)",
    bottom: 0,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  modalSheet: {
    alignSelf: "center",
    borderTopLeftRadius: Spacing.three,
    borderTopRightRadius: Spacing.three,
    gap: Spacing.three,
    maxHeight: "92%",
    maxWidth: MaxContentWidth,
    padding: Spacing.three,
    width: "100%",
  },
  guestModalOverlay: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
    padding: Spacing.three,
  },
  guestModalCard: {
    borderRadius: Spacing.three,
    gap: Spacing.three,
    maxHeight: "75%",
    maxWidth: 520,
    overflow: "hidden",
    padding: Spacing.three,
    width: "100%",
  },
  guestNameRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: Spacing.two,
  },
  guestNameInput: {
    flex: 1,
  },
  guestPositionOptions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.two,
  },
  guestAddButton: {
    alignItems: "center",
    backgroundColor: ActionColors.primary,
    borderRadius: Spacing.two,
    height: 48,
    justifyContent: "center",
    width: 48,
  },
  buttonDisabled: {
    opacity: 0.45,
  },
  guestHistorySection: {
    flexShrink: 1,
    gap: Spacing.two,
    minHeight: 0,
  },
  guestHistoryList: {
    flexShrink: 1,
    maxHeight: 280,
    minHeight: 0,
  },
  guestHistoryRow: {
    alignItems: "center",
    borderRadius: Spacing.two,
    flexDirection: "row",
    gap: Spacing.two,
    marginBottom: Spacing.one,
    minHeight: 48,
    paddingHorizontal: Spacing.two,
  },
  guestHistoryName: {
    flex: 1,
    gap: Spacing.one,
  },
  guestHistoryActions: {
    flexDirection: "row",
    gap: Spacing.one,
  },
  guestSquareAction: {
    alignItems: "center",
    borderRadius: Spacing.two,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  guestSquareAddAction: {
    backgroundColor: ActionColors.primary,
  },
  guestSquareDeleteAction: {
    backgroundColor: ActionColors.danger,
  },
  guestHistoryAddText: {
    color: "#536DFE",
  },
  shareModalSheet: {
    alignSelf: "center",
    borderTopLeftRadius: Spacing.three,
    borderTopRightRadius: Spacing.three,
    gap: Spacing.three,
    maxHeight: "94%",
    maxWidth: MaxContentWidth,
    padding: Spacing.three,
    width: "100%",
  },
  shareModalContent: {
    gap: Spacing.three,
    paddingBottom: Spacing.three,
  },
  shareOptionGroup: {
    gap: Spacing.one,
  },
  shareOptionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.two,
  },
  shareOptionButton: {
    borderColor: "#111827",
    borderRadius: Spacing.two,
    borderWidth: 1,
    paddingHorizontal: Spacing.three,
    paddingVertical: Spacing.two,
  },
  shareOptionButtonSelected: {
    backgroundColor: "#1C7C54",
    borderColor: "#1C7C54",
  },
  shareOptionButtonTextSelected: {
    color: "#FFFFFF",
  },
  shareColorPanel: {
    borderRadius: Spacing.three,
    gap: Spacing.two,
    padding: Spacing.three,
  },
  shareColorHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: Spacing.two,
    justifyContent: "space-between",
    width: "100%",
  },
  shareColorHeaderText: {
    flex: 1,
    minWidth: 0,
  },
  shareColorHeaderChevron: {
    flexShrink: 0,
  },
  shareColorSectionList: {
    gap: Spacing.three,
  },
  shareColorSection: {
    gap: Spacing.two,
  },
  shareColorFields: {
    gap: Spacing.two,
  },
  shareColorField: {
    gap: Spacing.one,
  },
  shareColorFieldHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  shareColorSwatchRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.one,
  },
  shareColorSwatch: {
    alignItems: "center",
    borderColor: "#D1D5DB",
    borderRadius: Spacing.one,
    borderWidth: 1,
    height: 28,
    justifyContent: "center",
    width: 28,
  },
  shareColorSwatchSelected: {
    borderColor: "#111827",
    borderWidth: 3,
  },
  sharePosterFrame: {
    aspectRatio: 1080 / 1350,
    backgroundColor: "#111827",
    position: "relative",
    width: "100%",
  },
  sharePosterBackground: {
    height: "100%",
    width: "100%",
  },
  posterOverlay: {
    ...StyleSheet.absoluteFill,
  },
  sharePosterLineupLayer: {
    ...StyleSheet.absoluteFill,
    position: "absolute",
  },
  sharePosterPlayer: {
    alignItems: "center",
    position: "absolute",
    transform: [{ translateX: -40 }, { translateY: -43 }],
    width: 79,
  },
  sharePosterSubstituteLayer: {
    ...StyleSheet.absoluteFill,
    position: "absolute",
    zIndex: 3,
  },
  sharePosterSubstitute: {
    alignItems: "center",
    position: "absolute",
    width: 78,
  },
  sharePosterSubstituteClassic: {
    transform: [{ translateX: -39 }, { translateY: -31 }, { scale: 0.52 }],
  },
  sharePosterSubstituteBroadcast: {
    transform: [{ translateX: -39 }, { translateY: -31 }, { scale: 0.58 }],
  },
  sharePosterLogoFrame: {
    alignItems: "center",
    height: 74,
    justifyContent: "center",
    position: "absolute",
    width: 74,
    zIndex: 2,
  },
  sharePosterLogo: {
    height: 58,
    opacity: 0.86,
    width: 58,
  },
  modalHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  modalTitleGroup: {
    flex: 1,
    gap: Spacing.one,
  },
  iconButton: {
    alignItems: "center",
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  formContent: {
    gap: Spacing.three,
    paddingBottom: Spacing.one,
  },
  resultStep: {
    gap: Spacing.three,
  },
  scoreboard: {
    alignItems: "center",
    flexDirection: "row",
    gap: Spacing.two,
  },
  scoreTeam: {
    alignItems: "center",
    flex: 1,
    gap: Spacing.two,
  },
  scoreDivider: {
    lineHeight: 38,
    marginTop: 26,
  },
  scoreStepper: {
    alignItems: "center",
    flexDirection: "row",
    gap: Spacing.two,
  },
  scoreStepperButton: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderColor: "#1C7C54",
    borderRadius: 999,
    borderWidth: 1.5,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  scoreValue: {
    minWidth: 44,
    textAlign: "center",
  },
  resultSummary: {
    borderRadius: Spacing.two,
    gap: Spacing.half,
    padding: Spacing.two,
  },
  resultReviewStep: {
    gap: Spacing.three,
  },
  resultSubstituteGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.one,
  },
  resultSubstituteRow: {
    alignItems: "center",
    borderRadius: Spacing.two,
    flexBasis: "31%",
    flexGrow: 1,
    minWidth: 78,
    padding: Spacing.one,
  },
  matchDutyResultRow: {
    alignItems: "center",
    borderRadius: Spacing.two,
    flexDirection: "row",
    gap: Spacing.two,
    minHeight: 44,
    paddingHorizontal: Spacing.two,
  },
  playerPerformanceStep: {
    gap: Spacing.three,
  },
  playerPerformanceList: {
    gap: Spacing.two,
  },
  playerResultEditorOverlay: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
    padding: Spacing.three,
  },
  playerResultEditorBackdrop: {
    backgroundColor: "rgba(0, 0, 0, 0.58)",
    bottom: 0,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  playerResultEditorCard: {
    borderRadius: Spacing.three,
    gap: Spacing.two,
    maxHeight: "90%",
    maxWidth: 560,
    padding: Spacing.three,
    width: "100%",
  },
  playerResultEditorHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 36,
  },
  playerResultEditorContent: {
    paddingBottom: Spacing.one,
  },
  playerResultEditorDoneButton: {
    width: "100%",
  },
  playerPerformanceCard: {
    borderRadius: Spacing.two,
    gap: Spacing.two,
    padding: Spacing.two,
  },
  playerPerformanceHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: Spacing.two,
    justifyContent: "space-between",
    minHeight: 48,
  },
  playerPerformanceTitleGroup: {
    flex: 1,
    gap: Spacing.half,
  },
  playerPerformanceControls: {
    gap: Spacing.three,
  },
  performanceControlRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.two,
  },
  statStepperGroup: {
    gap: Spacing.one,
    minWidth: 104,
  },
  statStepper: {
    alignItems: "center",
    flexDirection: "row",
    gap: Spacing.one,
  },
  statStepperButton: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderColor: "#1C7C54",
    borderRadius: 999,
    borderWidth: 1.5,
    height: 30,
    justifyContent: "center",
    width: 30,
  },
  statStepperValue: {
    minWidth: 28,
    textAlign: "center",
  },
  numericStepperGroup: {
    gap: Spacing.one,
  },
  numericStepper: {
    alignItems: "center",
    alignSelf: "flex-start",
    flexDirection: "row",
    gap: Spacing.one,
  },
  numericStepperInput: {
    backgroundColor: "#ffffff",
    borderColor: "#D1D5DB",
    borderWidth: 1,
    borderRadius: Spacing.two,
    fontSize: 16,
    fontWeight: "700",
    height: 40,
    paddingHorizontal: Spacing.two,
    textAlign: "center",
    width: 64,
  },
  resultSegmentedControl: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.one,
  },
  resultSegmentedOption: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderColor: "#1C7C54",
    borderRadius: Spacing.two,
    borderWidth: 1.5,
    justifyContent: "center",
    minHeight: 36,
    minWidth: 92,
    paddingHorizontal: Spacing.two,
  },
  resultSegmentedOptionSelected: {
    backgroundColor: "#1C7C54",
  },
  resultSegmentedOptionText: {
    color: "#1C7C54",
  },
  resultSegmentedOptionTextSelected: {
    color: "#ffffff",
  },
  subControlGroup: {
    gap: Spacing.two,
  },
  minutesSummary: {
    alignItems: "center",
    alignSelf: "flex-start",
    borderRadius: Spacing.two,
    flexDirection: "row",
    gap: Spacing.two,
    paddingHorizontal: Spacing.two,
    paddingVertical: Spacing.one,
  },
  availabilityStep: {
    gap: Spacing.three,
  },
  availabilityList: {
    gap: Spacing.two,
  },
  addGuestPlayerButton: {
    alignItems: "center",
    alignSelf: "stretch",
    backgroundColor: ActionColors.warning,
    borderRadius: Spacing.two,
    flexDirection: "row",
    gap: Spacing.one,
    justifyContent: "center",
    minHeight: 44,
    paddingHorizontal: Spacing.three,
  },
  addGuestPlayerButtonText: {
    color: "#ffffff",
  },
  availabilityRow: {
    alignItems: "center",
    borderRadius: Spacing.two,
    flexDirection: "row",
    gap: Spacing.two,
    minHeight: 64,
    padding: Spacing.two,
  },
  availabilityPlayerInfo: {
    flex: 1,
    gap: Spacing.half,
  },
  availabilityPlayerNameRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: Spacing.half,
  },
  availabilityToggle: {
    flexDirection: "row",
    gap: Spacing.one,
  },
  availabilityOption: {
    alignItems: "center",
    borderRadius: Spacing.two,
    justifyContent: "center",
    minHeight: 40,
    minWidth: 86,
    paddingHorizontal: Spacing.two,
  },
  availabilityOptionSelected: {
    backgroundColor: "#1C7C54",
  },
  availabilityOptionTextSelected: {
    color: "#ffffff",
  },
  responsibilityPanel: {
    borderRadius: Spacing.three,
    gap: Spacing.three,
    padding: Spacing.three,
  },
  responsibilityGroup: {
    gap: Spacing.two,
  },
  responsibilityOptions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.two,
  },
  playerRoleOption: {
    alignItems: "center",
    borderRadius: Spacing.two,
    justifyContent: "center",
    minHeight: 40,
    minWidth: 112,
    paddingHorizontal: Spacing.two,
  },
  playerRoleOptionSelected: {
    backgroundColor: "#536DFE",
  },
  playerRoleOptionTextSelected: {
    color: "#ffffff",
  },
  formationStep: {
    gap: Spacing.one,
  },
  reviewStep: {
    gap: Spacing.three,
  },
  reviewHeader: {
    gap: Spacing.half,
  },
  reviewOpponentRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: Spacing.two,
  },
  reviewOpponent: {
    flexShrink: 1,
    lineHeight: 38,
  },
  reviewPitch: {
    aspectRatio: 981 / 1604,
    borderRadius: Spacing.three,
    overflow: "visible",
    position: "relative",
    width: "100%",
  },
  reviewPitchImageClip: {
    borderRadius: Spacing.three,
    bottom: 0,
    left: 0,
    overflow: "hidden",
    position: "absolute",
    right: 0,
    top: 0,
  },
  reviewPitchPlayer: {
    alignItems: "center",
    backgroundColor: "transparent",
    height: 84,
    justifyContent: "center",
    marginLeft: -48,
    marginTop: -42,
    position: "absolute",
    width: 96,
  },
  reviewLists: {
    gap: Spacing.three,
  },
  reviewListSection: {
    gap: Spacing.two,
  },
  reviewRoleGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.two,
  },
  reviewRoleCard: {
    borderRadius: Spacing.two,
    flex: 1,
    gap: Spacing.half,
    minWidth: 148,
    padding: Spacing.two,
  },
  reviewPlayerGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.two,
  },
  reviewPlayerRow: {
    alignItems: "flex-start",
    flexBasis: "48%",
    flexDirection: "row",
    gap: Spacing.one,
    minWidth: 148,
  },
  reviewPlayerSlotLabel: {
    width: 32,
  },
  reviewPlayerName: {
    flexShrink: 1,
    lineHeight: 18,
    maxWidth: 190,
  },
  lineupDropSurface: {
    gap: Spacing.one,
    overflow: "visible",
  },
  fieldGroup: {
    gap: Spacing.two,
  },
  textInput: {
    borderRadius: Spacing.two,
    fontSize: 16,
    minHeight: 48,
    paddingHorizontal: Spacing.three,
    paddingVertical: Spacing.two,
  },
  multilineTextInput: {
    minHeight: 96,
    textAlignVertical: "top",
  },
  pickerButton: {
    alignItems: "center",
    borderRadius: Spacing.two,
    flexDirection: "row",
    gap: Spacing.two,
    minHeight: 48,
    paddingHorizontal: Spacing.three,
  },
  pickerDoneButton: {
    alignSelf: "flex-start",
    marginTop: Spacing.two,
  },
  segmentedControl: {
    flexDirection: "row",
    gap: Spacing.two,
  },
  segmentedOption: {
    alignItems: "center",
    borderRadius: Spacing.two,
    flex: 1,
    minHeight: 44,
    justifyContent: "center",
  },
  segmentedOptionSelected: {
    backgroundColor: "#1C7C54",
  },
  segmentedOptionTextSelected: {
    color: "#ffffff",
  },
  formationPicker: {
    gap: Spacing.two,
  },
  dropdownButton: {
    alignItems: "center",
    borderRadius: Spacing.two,
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 48,
    paddingHorizontal: Spacing.three,
    paddingVertical: Spacing.two,
  },
  dropdownMenu: {
    borderRadius: Spacing.two,
    gap: Spacing.one,
    padding: Spacing.two,
  },
  dropdownOption: {
    justifyContent: "center",
    minHeight: 44,
    paddingHorizontal: Spacing.three,
  },
  dropdownOptionSelected: {
    backgroundColor: "#1C7C54",
    borderRadius: Spacing.two,
  },
  dropdownOptionTextSelected: {
    color: "#ffffff",
  },
  pitch: {
    aspectRatio: 981 / 1604,
    borderRadius: Spacing.three,
    maxHeight: 720,
    overflow: "visible",
    position: "relative",
    width: "100%",
  },
  pitchImageClip: {
    borderRadius: Spacing.three,
    bottom: 0,
    left: 0,
    overflow: "hidden",
    position: "absolute",
    right: 0,
    top: 0,
  },
  pitchImage: {
    height: "100%",
    width: "100%",
  },
  pitchPlayersLayer: {
    backgroundColor: "transparent",
    bottom: 0,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  pitchSlot: {
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.58)",
    borderColor: "rgba(255, 255, 255, 0.82)",
    borderRadius: Spacing.three,
    borderWidth: 1,
    height: 48,
    justifyContent: "center",
    marginLeft: -24,
    marginTop: -24,
    position: "absolute",
    width: 48,
  },
  pitchSlotAssigned: {
    backgroundColor: "transparent",
    borderColor: "transparent",
    height: 98,
    marginLeft: -55,
    marginTop: -49,
    width: 110,
  },
  pitchSlotDragging: {
    zIndex: 10,
  },
  assignedPitchSlotButton: {
    alignItems: "center",
    height: "100%",
    justifyContent: "center",
    width: "100%",
  },
  pitchSlotPlus: {
    color: "#ffffff",
    lineHeight: 28,
  },
  pitchSlotLabel: {
    color: "#ffffff",
    lineHeight: 12,
    marginTop: -Spacing.one,
  },
  substituteSection: {
    gap: Spacing.one,
    marginTop: -Spacing.half,
  },
  substituteGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.two,
  },
  substituteSlot: {
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.18)",
    borderColor: "rgba(255, 255, 255, 0.54)",
    borderRadius: Spacing.three,
    borderWidth: 1,
    height: 98,
    justifyContent: "center",
    width: 88,
  },
  substituteSlotAssigned: {
    backgroundColor: "transparent",
    borderColor: "transparent",
  },
  substituteSlotPlus: {
    color: "#1C7C54",
    lineHeight: 36,
  },
  playerPickerOverlay: {
    flex: 1,
    justifyContent: "flex-end",
  },
  playerPickerSheet: {
    alignSelf: "center",
    borderTopLeftRadius: Spacing.three,
    borderTopRightRadius: Spacing.three,
    gap: Spacing.three,
    maxHeight: "72%",
    maxWidth: MaxContentWidth,
    padding: Spacing.three,
    width: "100%",
  },
  floatingPlayerActions: {
    alignItems: "center",
    borderRadius: Spacing.three,
    flexDirection: "row",
    gap: Spacing.one,
    marginLeft: -70,
    marginTop: -88,
    padding: Spacing.one,
    position: "absolute",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    zIndex: 20,
  },
  playerPickerHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  playerActionButton: {
    alignItems: "center",
    borderRadius: 18,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  playerActionButtonDanger: {
    backgroundColor: "#DC2626",
  },
  statsPopupOverlay: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
    padding: Spacing.three,
  },
  statsPopupCard: {
    borderColor: ActionColors.primary,
    borderRadius: Spacing.three,
    borderWidth: 1,
    gap: Spacing.two,
    maxWidth: 580,
    padding: Spacing.three,
    width: "100%",
  },
  statsPopupHeader: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: Spacing.two,
  },
  statsPopupTitleGroup: {
    flex: 1,
    gap: Spacing.one,
  },
  statsPopupName: {
    fontSize: 32,
    fontWeight: "700",
    lineHeight: 38,
  },
  statsPopupPosition: {
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 20,
  },
  statsPopupGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.one,
  },
  statsPopupPanel: {
    borderColor: ActionColors.primary,
    borderRadius: Spacing.three,
    borderWidth: 1,
    paddingHorizontal: Spacing.three,
    paddingVertical: Spacing.two,
  },
  statsPopupWidePanel: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "48%",
    minHeight: 88,
  },
  statsPopupMetricPanel: {
    alignItems: "center",
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "31%",
    minHeight: 82,
  },
  statsPopupPanelTitle: {
    color: ActionColors.primary,
    fontSize: 18,
    fontWeight: "700",
    lineHeight: 24,
  },
  statsPopupRatingList: {
    backgroundColor: "transparent",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.one,
    marginTop: Spacing.one,
  },
  statsPopupRatingPill: {
    alignItems: "center",
    borderRadius: Spacing.two,
    borderWidth: 1.5,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  statsPopupRatingGood: {
    borderColor: ActionColors.primary,
  },
  statsPopupRatingOk: {
    borderColor: ActionColors.warning,
  },
  statsPopupRatingPoor: {
    borderColor: ActionColors.danger,
  },
  statsPopupRatingText: {
    fontSize: 16,
    lineHeight: 20,
  },
  statsPopupRatingTextGood: {
    color: ActionColors.primary,
  },
  statsPopupRatingTextOk: {
    color: ActionColors.warning,
  },
  statsPopupRatingTextPoor: {
    color: ActionColors.danger,
  },
  statsPopupEmptyText: {
    marginTop: Spacing.two,
  },
  statsPopupLargeValue: {
    color: ActionColors.primary,
    fontSize: 28,
    fontWeight: "700",
    lineHeight: 34,
  },
  statsPopupSmallDetail: {
    fontSize: 12,
    lineHeight: 16,
  },
  statsPopupMetricTitle: {
    fontSize: 14,
    fontWeight: "700",
    lineHeight: 20,
    textAlign: "center",
  },
  statsPopupMetricValue: {
    color: ActionColors.primary,
    fontSize: 30,
    fontWeight: "700",
    lineHeight: 36,
    textAlign: "center",
  },
  playerPickerList: {
    gap: Spacing.two,
    paddingBottom: Spacing.one,
  },
  playerPickerItem: {
    alignItems: "center",
    borderRadius: Spacing.two,
    flexDirection: "row",
    gap: Spacing.two,
    minHeight: 56,
    paddingHorizontal: Spacing.three,
    paddingVertical: Spacing.two,
  },
  playerPickerItemSelected: {
    backgroundColor: "#D8F3DC",
  },
  playerPickerNameGroup: {
    flex: 1,
    gap: Spacing.half,
  },
  jerseyWrapper: {
    alignItems: "center",
    backgroundColor: "transparent",
    gap: Spacing.half,
    position: "relative",
    width: 108,
  },
  jerseyWrapperCompact: {
    width: 96,
  },
  jerseyWrapperDense: {
    width: 78,
  },
  jerseyShape: {
    alignItems: "center",
    backgroundColor: "transparent",
    height: 72,
    justifyContent: "center",
    position: "relative",
    width: 84,
  },
  jerseyShapeCompact: {
    height: 54,
    width: 64,
  },
  jerseyShapeDense: {
    height: 45,
    width: 53,
  },
  goalkeeperJerseyShape: {
    backgroundColor: "transparent",
  },
  jerseySvg: {
    height: "100%",
    position: "absolute",
    width: "100%",
  },
  jerseySvgCompact: {
    height: "100%",
    width: "100%",
  },
  jerseyNumber: {
    fontSize: 24,
    lineHeight: 28,
    marginTop: 10,
  },
  jerseyNumberLayer: {
    zIndex: 3,
  },
  jerseyNumberCompact: {
    fontSize: 16,
    lineHeight: 19,
    marginTop: 8,
  },
  jerseyNumberDense: {
    fontSize: 13,
    lineHeight: 16,
    marginTop: 6,
  },
  jerseyNameRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: Spacing.half,
    justifyContent: "center",
    width: 108,
  },
  jerseyNameRowCompact: {
    width: 96,
  },
  jerseyNameRowDense: {
    width: 78,
  },
  captainBadge: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#111827",
    borderRadius: 999,
    borderWidth: 1,
    height: 22,
    justifyContent: "center",
    position: "absolute",
    right: 0,
    top: -3,
    width: 22,
    zIndex: 12,
  },
  captainBadgeCompact: {
    height: 17,
    right: 5,
    top: -4,
    width: 17,
  },
  captainBadgeDense: {
    height: 16,
    right: -1,
    top: -2,
    width: 16,
  },
  captainBadgeText: {
    color: "#111827",
    fontSize: 14,
    lineHeight: 16,
  },
  captainBadgeTextCompact: {
    fontSize: 10,
    lineHeight: 12,
  },
  captainBadgeTextDense: {
    fontSize: 9,
    lineHeight: 11,
  },
  jerseyName: {
    // backgroundColor: "rgba(15, 23, 42, 0.62)",
    borderRadius: Spacing.one,
    color: "#ffffff",
    flexShrink: 1,
    lineHeight: 16,
    maxWidth: 108,
    paddingHorizontal: Spacing.one,
    textAlign: "center",
    textShadowColor: "#000000",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  jerseyNameCompact: {
    maxWidth: 96,
  },
  jerseyNameDense: {
    lineHeight: 16,
    maxWidth: 78,
  },
  jerseyResultOverlay: {
    backgroundColor: "transparent",
    bottom: 0,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
    zIndex: 8,
  },
  jerseyResultOverlayCompact: {
    bottom: -1,
    left: -4,
    right: -4,
    top: -1,
  },
  jerseyResultIconBadge: {
    alignItems: "center",
    borderRadius: 999,
    height: 24,
    justifyContent: "center",
    overflow: "hidden",
    position: "absolute",
    width: 24,
  },
  jerseyResultIconBadgeCompact: {
    height: 20,
    width: 20,
  },
  jerseyResultSubBadge: {
    left: 5,
    top: -4,
  },
  jerseyResultCardShell: {
    alignItems: "center",
    borderRadius: 999,
    height: 26,
    justifyContent: "center",
    left: -2,
    overflow: "hidden",
    position: "absolute",
    top: 29,
    width: 26,
  },
  jerseyResultCardShellCompact: {
    height: 20,
    left: 5,
    top: 17,
    width: 20,
  },
  jerseyResultEventBadge: {
    alignItems: "center",
    borderRadius: 999,
    height: 26,
    justifyContent: "center",
    overflow: "hidden",
    width: 26,
    zIndex: 1,
  },
  jerseyResultEventBadgeCompact: {
    height: 20,
    width: 20,
  },
  jerseyResultGoalStack: {
    alignItems: "center",
    bottom: -2,
    height: 26,
    left: 5,
    position: "absolute",
    width: 26,
  },
  jerseyResultGoalStackCompact: {
    height: 20,
    width: 20,
  },
  jerseyResultGoalBadge: {
    position: "absolute",
  },
  jerseyResultAssistStack: {
    alignItems: "center",
    bottom: -2,
    height: 26,
    position: "absolute",
    right: 5,
    width: 26,
  },
  jerseyResultAssistStackCompact: {
    height: 20,
    width: 20,
  },
  jerseyResultAssistBadge: {
    backgroundColor: "#111827",
    overflow: "hidden",
    padding: 0,
    position: "absolute",
  },
  jerseyResultAssistImage: {
    height: 26,
    width: 26,
  },
  jerseyResultAssistImageCompact: {
    height: 20,
    width: 20,
  },
  jerseyResultImageBadge: {
    height: "100%",
    width: "100%",
  },
  jerseyResultImageBadgeCompact: {
    height: "100%",
    width: "100%",
  },
  jerseyResultEventCount: {
    backgroundColor: "#111827",
    borderRadius: 999,
    color: "#ffffff",
    fontSize: 8,
    lineHeight: 10,
    minWidth: 11,
    overflow: "hidden",
    position: "absolute",
    right: -4,
    textAlign: "center",
    top: -4,
    zIndex: 20,
  },
  removePlayerButton: {
    alignItems: "center",
    alignSelf: "stretch",
    backgroundColor: "transparent",
    borderColor: "#DC2626",
    borderRadius: Spacing.two,
    borderWidth: 1.5,
    justifyContent: "center",
    minHeight: 44,
    paddingHorizontal: Spacing.three,
  },
  removePlayerButtonText: {
    color: "#DC2626",
  },
  formActions: {
    flexDirection: "row",
    gap: Spacing.two,
    justifyContent: "flex-end",
  },
  reviewActions: {
    flexDirection: "row",
    gap: Spacing.one,
  },
  reviewActionButton: {
    alignItems: "center",
    borderRadius: Spacing.three,
    flex: 1,
    justifyContent: "center",
    minHeight: 52,
    paddingHorizontal: Spacing.two,
  },
  reviewBackButton: {
    backgroundColor: "transparent",
    borderColor: "#7A7A7A",
    borderWidth: 1.5,
  },
  reviewShareButton: {
    backgroundColor: ActionColors.warning,
  },
  reviewSaveButton: {
    backgroundColor: ActionColors.primary,
    borderColor: ActionColors.primary,
    borderWidth: 1.5,
    flex: 1.35,
  },
  reviewSaveButtonText: {
    color: ActionColors.onAccent,
    textAlign: "center",
  },
  reviewActionText: {
    color: "#ffffff",
  },
  reviewBackButtonText: {
    color: "#7A7A7A",
  },
  secondaryButton: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderColor: "#7A7A7A",
    borderRadius: Spacing.two,
    borderWidth: 1.5,
    justifyContent: "center",
    minHeight: 44,
    paddingHorizontal: Spacing.three,
  },
  sharePosterButton: {
    alignItems: "center",
    backgroundColor: ActionColors.warning,
    borderRadius: Spacing.two,
    justifyContent: "center",
    minHeight: 44,
    paddingHorizontal: Spacing.three,
  },
  sharePosterButtonText: {
    color: ActionColors.onAccent,
  },
  primaryButton: {
    alignItems: "center",
    backgroundColor: "#1C7C54",
    borderRadius: Spacing.two,
    justifyContent: "center",
    minHeight: 44,
    paddingHorizontal: Spacing.three,
  },
  disabledButton: {
    opacity: 0.55,
  },
  primaryButtonText: {
    color: "#ffffff",
  },
});
